language: ruby
sudo: false
rvm:
  - 2.3.0
script:
  - bundle exec middleman build
before_deploy:
  - openssl aes-256-cbc -K $encrypted_c5cd5eb45301_key -iv $encrypted_c5cd5eb45301_iv -in deploy_key.enc -out deploy_key -d
  - chmod 600 deploy_key
deploy:
  provider: script
  skip_cleanup: true
  script:
    - "./bin/deploy"
  on:
    branch: master
